### ISSUE TITLE
Update all failed

### ISSUE THREAD

**Issue by nathanielcutajar** [Neocky/pluGET#36]
**Describe the bug**
Tried updating everything in the hub that was just upgraded from 1.13 to 1.15 and it threw an error

**To Reproduce**
0) (Not sure if it matters but) Update from 1.13 to 1.15
1) Check all for updates
2) Run update all command

**Expected behavior**
Plugins should be downloaded or at least ignore the bad plugin and update the rest

**Screenshots**
![image](https://user-images.githubusercontent.com/9025825/126062315-4cd9800d-c6e1-421f-8e3c-9563b57ed9ac.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (5.4.0-77-generic)

**Additional context**
N/A

**Comment by nathanielcutajar** [comment]
I could update all the other plugins individually but not AsyncWorldEdit

**Comment by Neocky** [comment]
#### Hey @nathanielcutajar, 
thank you for your bug report!
You can't update AsyncWorldEdit because the file isn't hosted on spigotmc. When you click download on it, it will redirect you to github. pluGET stopped the updating because of that.
I fixed that and now it will just skip the plugin if it can't download it in the new version: [v1.6.6](https://github.com/Neocky/pluGET/releases/tag/v1.6.6)
Update to the latest version and pluGET won't crash anymore when it can't download the file.

Sadly PremiumVanish is a paid ressource and can't be updated with pluGET.

### Thank you for flying with pluGET 🚀
